# fly.toml app configuration file generated for alchemy-demo on 2023-05-26T09:23:34+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "alchemy-demo"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  [build.args]
    BUILD_COMMAND = "bin/rails fly:build"
    SERVER_COMMAND = "bin/rails fly:server"

[deploy]
  release_command = "bin/rails fly:release"

[env]
  DATABASE_CLEANER_ALLOW_PRODUCTION = "true"
  DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL = "true"
  DISABLE_DATABASE_ENVIRONMENT_CHECK = "1"
  NEW_RELIC_LOG = "stdout"
  PORT = "8080"

[[services]]
  protocol = "tcp"
  internal_port = 8080
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = "15s"
    timeout = "2s"
    grace_period = "1s"
    restart_limit = 0

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
