services:
  - name: alchemy-demo-rails
    type: web
    env: ruby
    region: frankfurt
    plan: free
    repo: https://github.com/AlchemyCMS/alchemy-demo.git
    numInstances: 1
    healthCheckPath: /healthz
    buildCommand: bin/build
    initialDeployHook: bin/rake db:seed
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - fromGroup: alchemy-demo-env-vars
      - fromGroup: alchemy-demo-secrets
      - key: DATABASE_URL
        fromDatabase:
          name: alchemy-demo-postgres
          property: connectionString
      - key: REDIS_HOST
        fromService:
          name: alchemy-demo-redis
          property: host
          type: redis
      - key: REDIS_PORT
        fromService:
          name: alchemy-demo-redis
          property: port
          type: redis

  - name: alchemy-demo-redis
    type: redis
    region: frankfurt
    plan: free
    maxmemoryPolicy: volatile-lru
    ipAllowList:
      - source: 90.187.213.217/32
        description: Blish (office)

databases:
  - name: alchemy-demo-postgres
    region: frankfurt
    plan: free
    ipAllowList:
      - source: 90.187.213.217/32
        description: Blish (office)

envVarGroups:
  - name: alchemy-demo-env-vars
    envVars:
      - key: RAILS_ENV
        value: production
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true
      - key: LD_PRELOAD
        value: /usr/lib/x86_64-linux-gnu/libjemalloc.so.2
      - key: DATABASE_CLEANER_ALLOW_PRODUCTION
        value: true
      - key: DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL
        value: true
      - key: DISABLE_DATABASE_ENVIRONMENT_CHECK
        value: 1
      - key: NEW_RELIC_LOG
        value: stdout
